In [2]:
import numpy as np

In [10]:
arr = np.random.rand(5,5)

In [7]:
arr

array([[0.19464098, 0.19120625, 0.15660022, 0.02795923, 0.43827447],
       [0.67866799, 0.25488603, 0.31614752, 0.08500209, 0.07481133],
       [0.56638862, 0.79911549, 0.8790465 , 0.9604059 , 0.04352569],
       [0.94637739, 0.59230388, 0.65898374, 0.90365144, 0.25719279],
       [0.33428943, 0.42453112, 0.00850432, 0.57661131, 0.14491028]])

In [3]:
arr = np.random.randint(0, 10, size=(5, 5))
print(arr)

[[0 9 5 9 0]
 [7 6 3 4 3]
 [8 7 3 2 5]
 [1 6 0 9 5]
 [1 4 5 4 7]]


In [4]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


### element-wise addition, subtraction, multiplication and division

In [4]:
print(arr + 10)
print(arr - 10)
print(arr * 10)
print(arr / 10)

[11 12 13 14 15]
[-9 -8 -7 -6 -5]
[10 20 30 40 50]
[0.1 0.2 0.3 0.4 0.5]


In [4]:
# the above operations can be performed using numpy built-in functions
# which can save memory as the output can be stored in the original array rather than assigning new memory
arr1 = np.array([1,2,3])
np.add(arr1, [8,9,10], out=arr1)
print(arr1)

np.subtract(arr1, [8,9,10], out=arr1)
print(arr1)

np.multiply(arr1, [1,2,3], out=arr1)
print(arr1)

[ 9 11 13]
[1 2 3]
[1 4 9]


### element-wise exponentiation

In [5]:
print(np.exp(arr))

[[2.14478615 1.06342678 1.78433068 2.29142547 1.41777901]
 [2.22276554 2.26037915 1.39463534 2.57938054 1.30904357]
 [2.49238988 1.43749547 1.61345052 1.11713487 1.15168052]
 [1.51528302 1.0890368  1.82891972 1.02283095 1.5669926 ]
 [1.42963827 2.11099066 1.91901017 2.50826279 1.02239337]]


### element-wise logorithm

In [ ]:
# natural log
print(np.log(arr))

[[-0.27044502 -2.78877489 -0.54637789 -0.18732513 -1.05242102]
 [-0.22470457 -0.20391393 -1.10071557 -0.05387634 -1.31194126]
 [-0.09075433 -1.01362151 -0.7373602  -2.2003241  -1.95742073]
 [-0.87802664 -2.46165544 -0.5046357  -3.79094655 -0.80038003]
 [-1.02883965 -0.29147948 -0.42800291 -0.08382693 -3.81008411]]


In [7]:
# base 2
print(np.log2(arr))     

[[-0.39016969 -4.02335171 -0.78825668 -0.27025304 -1.51832258]
 [-0.32418017 -0.29418561 -1.5879969  -0.07772714 -1.89273115]
 [-0.13093082 -1.46234672 -1.0637859  -3.17439666 -2.82396118]
 [-1.26672468 -3.55141809 -0.72803542 -5.46917978 -1.1547043 ]
 [-1.48430185 -0.42051601 -0.61747768 -0.12093669 -5.49678945]]


In [8]:
# base 10
print(np.log10(arr))    

[[-0.11745278 -1.21114955 -0.2372889  -0.08135427 -0.45706064]
 [-0.09758796 -0.08855869 -0.4780347  -0.0233982  -0.56976885]
 [-0.0394141  -0.44021023 -0.32023147 -0.95558861 -0.85009702]
 [-0.38132213 -1.06908337 -0.2191605  -1.64638717 -0.34760063]
 [-0.44681938 -0.12658793 -0.1858793  -0.03640557 -1.65469851]]


### element-wise square root

In [5]:
print(np.sqrt(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]


### element-wise sine and cosine

In [10]:
print(np.sin(arr))

[[0.69112165 0.06145775 0.5472235  0.73737374 0.34204431]
 [0.71648615 0.72809076 0.32653281 0.81198751 0.26605362]
 [0.79148938 0.35498904 0.46033726 0.11054088 0.14075325]
 [0.40374097 0.08519025 0.56771331 0.02257231 0.43420742]
 [0.34985981 0.67955607 0.60662594 0.79535341 0.02214451]]


In [11]:
print(np.cos(arr))

[[0.72273845 0.99810969 0.83698652 0.67548499 0.93968382]
 [0.69760131 0.68548074 0.94518587 0.5836748  0.96395823]
 [0.61118293 0.93487046 0.88774411 0.99387158 0.99004471]
 [0.91487334 0.9963647  0.82322633 0.99974521 0.90081292]
 [0.93680207 0.73362358 0.7949874  0.60614599 0.99975478]]


### sum along a specified axis

In [12]:
arr


array([[6, 3, 4, 7, 7],
       [5, 4, 3, 9, 2],
       [3, 3, 1, 1, 9],
       [4, 1, 2, 1, 6],
       [1, 7, 3, 4, 3]], dtype=int32)

In [13]:
# sum along the column
print(np.sum(arr, axis=0))    

[19 18 13 22 27]


In [14]:
# sum along the row
print(np.sum(arr, axis=1))    

[27 23 17 14 18]


### compute the min and max along a specified axis

In [15]:
arr

array([[6, 3, 4, 7, 7],
       [5, 4, 3, 9, 2],
       [3, 3, 1, 1, 9],
       [4, 1, 2, 1, 6],
       [1, 7, 3, 4, 3]], dtype=int32)

In [16]:
# calculate min along the column
print(np.min(arr, axis=0))

[1 1 1 1 2]


In [17]:
# calculate max along the row
print(np.max(arr, axis=1))    

[7 9 9 6 7]


In [18]:
# if axis not specified, calculate the max/min value of all elements
print(np.max(arr))
print(np.min(arr))

9
1


### compute the indices of the min and max along a specified axis

In [17]:
# along the row
print(np.argmin(arr, axis=0))
print(np.argmax(arr, axis=0))

[4 0 1 3 4]
[2 1 4 1 3]


In [18]:
# along the column
print(np.argmin(arr, axis=1))
print(np.argmax(arr, axis=1))

[1 4 3 3 4]
[3 3 0 2 3]


In [19]:
# if axis not specified, return the index of the flattened array
print(np.argmin(arr))
print(np.argmax(arr))

24
8


### compute element-wise min and max of two arrays

In [20]:
arr1 = np.array([1, 3, 5, 7, 9])
arr2 = np.array([0, 4, 3, 8, 7])
print(np.maximum(arr1, arr2))
print(np.minimum(arr1, arr2))

[1 4 5 8 9]
[0 3 3 7 7]


### split fractional and integral parts of a floating-point array

In [9]:
arr1 = np.random.rand(10) * 10
print(arr1)
re, intg = np.modf(arr1)
print('fractional: ', re)
print('integral: ', intg)

[1.9398881  1.77169276 9.05950234 3.13322605 5.49630829 3.59013922
 3.58684724 5.21740394 2.24975854 2.45122375]
fractional:  [0.9398881  0.77169276 0.05950234 0.13322605 0.49630829 0.59013922
 0.58684724 0.21740394 0.24975854 0.45122375]
integral:  [1. 1. 9. 3. 5. 3. 3. 5. 2. 2.]


### compute the mean

In [22]:
# compute the overall mean
print(np.mean(arr))

0.4810638752799312


In [ ]:
# compute the mean along the row
print(np.mean(arr, axis=0))    

[0.64961155 0.41447648 0.52911728 0.56593105 0.24618302]


In [24]:
# compute the mean along the column
print(np.mean(arr, axis=1)) 

[0.51636908 0.63275275 0.40130178 0.31527076 0.53962501]


### compute the median

In [25]:
# compute the overall median
print(np.median(arr))

0.4491582392434029


In [26]:
# compute the median along the row
print(np.median(arr, axis=0)) 

[0.76303985 0.36290234 0.57904337 0.8291741  0.26929677]


In [27]:
# compute the median along the column
print(np.median(arr, axis=1))

[0.57904337 0.79875216 0.36290234 0.41560224 0.65180952]


### compute the percentile

In [28]:
arr1 = np.random.rand(100)
# compute 5, 65, and 95 percentiles of the array
print(np.percentile(arr1, [5, 65, 95]))

[0.02821037 0.5914621  0.89273939]


[55, 60, 65, 70, 75, 80, 85, 90, 95, 100]
The 50th percentile is the median → 75 (half the values are below it).

The 90th percentile is 95 → 90% of values are less than or equal to 95.

The 25th percentile is 65 → 25% of values are less than or equal to 65.

### compute the standard deviation & variance

In [29]:
# compute the overall standard deviation
print(np.std(arr))

0.3006485476445816


In [30]:
# compute the standard deviation along the row
print(np.std(arr, axis=0))

[0.22124437 0.3184772  0.11339598 0.41046681 0.15068681]


In [31]:
# compute the standard deviation along the column
print(np.std(arr, axis=1))

[0.28196182 0.27648987 0.29036161 0.22349905 0.31654733]


In [32]:
# compute the overall variance
print(np.var(arr))

0.09038954920079624


In [33]:
# compute the variance along the row
print(np.var(arr, axis=0))

[0.04894907 0.10142773 0.01285865 0.168483   0.02270651]


In [34]:
# compute the variance along the column
print(np.var(arr, axis=1))

[0.07950247 0.07644665 0.08430987 0.04995182 0.10020221]


### compute cumulative sum & product

In [21]:
arr

array([[6, 3, 4, 7, 7],
       [5, 4, 3, 9, 2],
       [3, 3, 1, 1, 9],
       [4, 1, 2, 1, 6],
       [1, 7, 3, 4, 3]], dtype=int32)

In [22]:
# calculate the cumulative sums along the row
print(np.cumsum(arr, axis=0))    

[[ 6  3  4  7  7]
 [11  7  7 16  9]
 [14 10  8 17 18]
 [18 11 10 18 24]
 [19 18 13 22 27]]


In [23]:
# calculate the cumulative sums along the column
print(np.cumsum(arr, axis=1))    

[[ 6  9 13 20 27]
 [ 5  9 12 21 23]
 [ 3  6  7  8 17]
 [ 4  5  7  8 14]
 [ 1  8 11 15 18]]


In [ ]:
arr = [1, 2, 3, 4]
[1, 1+2, 1+2+3, 1+2+3+4] → [1, 3, 6, 10]
[1, 1×2, 1×2×3, 1×2×3×4] → [1, 2, 6, 24]

In [24]:
# calculate the cumulative product along the row
print(np.cumprod(arr, axis=0))   

[[   6    3    4    7    7]
 [  30   12   12   63   14]
 [  90   36   12   63  126]
 [ 360   36   24   63  756]
 [ 360  252   72  252 2268]]


In [25]:
# calculate the cumulative product along the column
print(np.cumprod(arr, axis=1))  

[[   6   18   72  504 3528]
 [   5   20   60  540 1080]
 [   3    9    9    9   81]
 [   4    4    8    8   48]
 [   1    7   21   84  252]]


### element-wise comparison

In [42]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1])

In [43]:
# return an array of bools
print(arr1 == arr2)    
print(arr1 < 3)

[False False  True False False]
[ True  True False False False]
