In [1]:
import numpy as np

In [2]:
arr = np.random.rand(5,5)
arr

array([[0.96722848, 0.69368184, 0.74929279, 0.29242624, 0.58079295],
       [0.54303713, 0.19763302, 0.87629951, 0.58638383, 0.51312949],
       [0.04128896, 0.03006384, 0.84243596, 0.59195734, 0.05205803],
       [0.52356587, 0.43534239, 0.77225167, 0.43541763, 0.29691184],
       [0.14045704, 0.87931766, 0.80903894, 0.63980419, 0.08332471]])

### sort an array along a specified axis

In [5]:
# sort along the row and return a copy
print(np.sort(arr, axis=0))   

[[0.11341692 0.29932278 0.08090573 0.09950953 0.32324335]
 [0.15978044 0.62752158 0.20318513 0.11953778 0.41544285]
 [0.16302597 0.65055433 0.33310378 0.26874928 0.83249185]
 [0.2215239  0.72245392 0.37860696 0.42462771 0.93883775]
 [0.90089263 0.84680563 0.67612359 0.51745198 0.989452  ]]


In [4]:
# sort along the row in place
arr.sort(axis=0)
print(arr)

[[0.32367677 0.160538   0.07577069 0.02051216 0.23410999]
 [0.54927129 0.20910696 0.2196075  0.22756129 0.67417506]
 [0.63553217 0.56279363 0.62776371 0.32657277 0.79901529]
 [0.7183594  0.69288395 0.70838123 0.52581954 0.96520237]
 [0.81701677 0.79908087 0.98800108 0.54773388 0.97694313]]


In [5]:
# sort along the column and return a copy
print(np.sort(arr, axis=1))    

[[0.02051216 0.07577069 0.160538   0.23410999 0.32367677]
 [0.20910696 0.2196075  0.22756129 0.54927129 0.67417506]
 [0.32657277 0.56279363 0.62776371 0.63553217 0.79901529]
 [0.52581954 0.69288395 0.70838123 0.7183594  0.96520237]
 [0.54773388 0.79908087 0.81701677 0.97694313 0.98800108]]


In [6]:
# sort along the column in place
arr.sort(axis=1)    
print(arr)

[[0.02051216 0.07577069 0.160538   0.23410999 0.32367677]
 [0.20910696 0.2196075  0.22756129 0.54927129 0.67417506]
 [0.32657277 0.56279363 0.62776371 0.63553217 0.79901529]
 [0.52581954 0.69288395 0.70838123 0.7183594  0.96520237]
 [0.54773388 0.79908087 0.81701677 0.97694313 0.98800108]]
