In [2]:
import numpy as np

In [37]:
arr = np.random.rand(3,4)
arr

array([[0.57816747, 0.94550713, 0.47311654, 0.52635639],
       [0.24799765, 0.34792288, 0.44455591, 0.58171468],
       [0.98072577, 0.72420907, 0.93602061, 0.9888003 ]])

In [9]:
arr = np.random.randint(0, 10, size=(5, 5))
print(arr)

[[8 1 7 3 0]
 [6 8 4 1 5]
 [7 0 3 8 2]
 [5 2 3 3 0]
 [1 2 9 0 4]]


### transpose an array

In [4]:
arr.T

array([[2, 8, 1, 1, 4],
       [9, 1, 4, 6, 4],
       [8, 7, 1, 6, 5],
       [6, 1, 1, 8, 0],
       [4, 6, 2, 8, 0]], dtype=int32)

In [3]:
# the following methods return a copy
print(arr.T)
# or 
print(np.transpose(arr))
# or
print(arr.transpose())

[[2 9 2 4 5]
 [1 2 3 4 7]
 [7 5 4 2 1]
 [1 7 0 7 7]
 [4 4 5 4 1]]
[[2 9 2 4 5]
 [1 2 3 4 7]
 [7 5 4 2 1]
 [1 7 0 7 7]
 [4 4 5 4 1]]
[[2 9 2 4 5]
 [1 2 3 4 7]
 [7 5 4 2 1]
 [1 7 0 7 7]
 [4 4 5 4 1]]


### transpose of a high dimensional array with specified order of axes

In [ ]:
2 blocks (or outermost arrays)

Each block has 2 rows

Each row has 4 columns

In [6]:
arr1 = np.arange(16).reshape((2,2,4))
arr1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [7]:
arr1.ndim

3

In [36]:
arr1 = np.arange(16).reshape((2,2,4))
print(arr1)

# #  first two axes swapped.
arr2 = arr1.transpose((1,0,2))
print(arr2)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


### swap axes

In [14]:
arr1 = np.arange(16).reshape((2,2,4))
print(arr1)
print(arr1.swapaxes(1,2))

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


In [38]:
arr

array([[0.57816747, 0.94550713, 0.47311654, 0.52635639],
       [0.24799765, 0.34792288, 0.44455591, 0.58171468],
       [0.98072577, 0.72420907, 0.93602061, 0.9888003 ]])

### change the shape of an array

In [13]:
arr = np.arange(12)

In [14]:
# change the shape of an array and return a copy
arr.reshape((2,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
# change the shape of an array in place
arr.resize((2,6))


In [17]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

### flatten an array

In [18]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [19]:
# return a copy
arr.flatten()    

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
arr

array([[0.73747633, 0.20131797, 0.35884544, 0.40388853],
       [0.51878923, 0.19830114, 0.45207528, 0.15196706],
       [0.06152812, 0.74966553, 0.8081083 , 0.91780935]])

### append elements to an array

In [20]:
arr = np.array([1,2,3])

In [21]:
# append a scalar and return a copy
arr1 = np.append(arr, 4)    
print(arr1)

[1 2 3 4]


In [23]:
# append an array and return a copy
arr2 = np.append(arr1, [4,5,6])    
print(arr2)

[1 2 3 4 4 5 6]


### insert elements into an array

In [13]:
# np.insert(array, position, element)

# insert a scalar at a certain position
arr3 = np.insert(arr, 0, 100)    
print(arr3)

[100   1   2   3]


In [46]:
# insert multiple values at a certain position
arr3 = np.insert(arr, 0, [5,7,8])    
print(arr3)

[5 7 8 1 2 3]


### delete elements from an array

In [15]:
# remove the element at position 0
arr4 = np.delete(arr, 0)    
print(arr4)

[2 3]


In [16]:
# remove the element at multiple positions
arr4 = np.delete(arr, [0,2])    
print(arr4)

[2]


### copy an array

In [17]:
arr = np.array([1,2,3])

In [24]:
# the following methods are all copy
arr1 = np.copy(arr)
# or 
arr1 = arr.copy()
# or 
arr1 = np.array(arr, copy=True)