In [2]:
import numpy as np

In [3]:
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])

In [4]:
arr1

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [5]:
arr2

array([[5, 6, 7, 8],
       [5, 6, 7, 8]])

### ```np.concatenate((a, b), axis=0)```

In [3]:
# concat along the row
cat = np.concatenate((arr1, arr2), axis=0)        
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [6]:
# concat along the column
cat = np.concatenate((arr1, arr2), axis=1)    
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### ```np.vstack((a, b))``` 
### ```np.r_[a, b]```

In [5]:
# stack arrays vertically
cat = np.vstack((arr1, arr2))
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [6]:
# stack arrays vertically
cat = np.r_[arr1, arr2]
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


### ```np.hstack((a, b))```
### ```np.c_[a, b]```

In [6]:
# stack arrays horizontally
cat = np.hstack((arr2, arr1))
print(cat)

[[5 6 7 8 1 2 3 4]
 [5 6 7 8 1 2 3 4]]


In [8]:
# stack arrays horizontally
cat = np.c_[arr1, arr2]
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### split an array 

In [9]:
arr = np.random.rand(6,6)
arr

array([[0.92687996, 0.7680779 , 0.56959967, 0.11221846, 0.66319614,
        0.80126339],
       [0.43384607, 0.08350672, 0.18109681, 0.85307852, 0.38433865,
        0.64879406],
       [0.46350709, 0.78543467, 0.17750698, 0.45684951, 0.69001992,
        0.63694663],
       [0.53469983, 0.24735511, 0.86811902, 0.90804035, 0.9035731 ,
        0.42544033],
       [0.62610869, 0.09740873, 0.50794975, 0.65400186, 0.89540174,
        0.59349878],
       [0.12440556, 0.25984282, 0.3650099 , 0.75030035, 0.62968706,
        0.69822031]])

In [10]:
# split the array vertically into n evenly spaced chunks
arr1 = np.vsplit(arr, 2)
print(arr1)

[array([[0.92687996, 0.7680779 , 0.56959967, 0.11221846, 0.66319614,
        0.80126339],
       [0.43384607, 0.08350672, 0.18109681, 0.85307852, 0.38433865,
        0.64879406],
       [0.46350709, 0.78543467, 0.17750698, 0.45684951, 0.69001992,
        0.63694663]]), array([[0.53469983, 0.24735511, 0.86811902, 0.90804035, 0.9035731 ,
        0.42544033],
       [0.62610869, 0.09740873, 0.50794975, 0.65400186, 0.89540174,
        0.59349878],
       [0.12440556, 0.25984282, 0.3650099 , 0.75030035, 0.62968706,
        0.69822031]])]


In [11]:
# split the array horizontally into n evenly spaced chunks
arr2 = np.hsplit(arr, 2)
print(arr2)

[array([[0.92687996, 0.7680779 , 0.56959967],
       [0.43384607, 0.08350672, 0.18109681],
       [0.46350709, 0.78543467, 0.17750698],
       [0.53469983, 0.24735511, 0.86811902],
       [0.62610869, 0.09740873, 0.50794975],
       [0.12440556, 0.25984282, 0.3650099 ]]), array([[0.11221846, 0.66319614, 0.80126339],
       [0.85307852, 0.38433865, 0.64879406],
       [0.45684951, 0.69001992, 0.63694663],
       [0.90804035, 0.9035731 , 0.42544033],
       [0.65400186, 0.89540174, 0.59349878],
       [0.75030035, 0.62968706, 0.69822031]])]
